// This file is generated by rust-protobuf 2.8.1. Do not edit
// @generated

// https://github.com/Manishearth/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![cfg_attr(rustfmt, rustfmt_skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unsafe_code)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `src/io/handshake/payload.proto`

use protobuf::Message as Message_imported_for_functions;
use protobuf::ProtobufEnum as ProtobufEnum_imported_for_functions;

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_8_1;

#[derive(PartialEq,Clone,Default)]
pub struct NoiseHandshakePayload {
    // message fields
    pub identity_key: ::std::vec::Vec<u8>,
    pub identity_sig: ::std::vec::Vec<u8>,
    pub data: ::std::vec::Vec<u8>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a NoiseHandshakePayload {
    fn default() -> &'a NoiseHandshakePayload {
        <NoiseHandshakePayload as ::protobuf::Message>::default_instance()
    }
}

impl NoiseHandshakePayload {
    pub fn new() -> NoiseHandshakePayload {
        ::std::default::Default::default()
    }

    // bytes identity_key = 1;


    pub fn get_identity_key(&self) -> &[u8] {
        &self.identity_key
    }
    pub fn clear_identity_key(&mut self) {
        self.identity_key.clear();
    }

    // Param is passed by value, moved
    pub fn set_identity_key(&mut self, v: ::std::vec::Vec<u8>) {
        self.identity_key = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_identity_key(&mut self) -> &mut ::std::vec::Vec<u8> {
        &mut self.identity_key
    }

    // Take field
    pub fn take_identity_key(&mut self) -> ::std::vec::Vec<u8> {
        ::std::mem::replace(&mut self.identity_key, ::std::vec::Vec::new())
    }

    // bytes identity_sig = 2;


    pub fn get_identity_sig(&self) -> &[u8] {
        &self.identity_sig
    }
    pub fn clear_identity_sig(&mut self) {
        self.identity_sig.clear();
    }

    // Param is passed by value, moved
    pub fn set_identity_sig(&mut self, v: ::std::vec::Vec<u8>) {
        self.identity_sig = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_identity_sig(&mut self) -> &mut ::std::vec::Vec<u8> {
        &mut self.identity_sig
    }

    // Take field
    pub fn take_identity_sig(&mut self) -> ::std::vec::Vec<u8> {
        ::std::mem::replace(&mut self.identity_sig, ::std::vec::Vec::new())
    }

    // bytes data = 3;


    pub fn get_data(&self) -> &[u8] {
        &self.data
    }
    pub fn clear_data(&mut self) {
        self.data.clear();
    }

    // Param is passed by value, moved
    pub fn set_data(&mut self, v: ::std::vec::Vec<u8>) {
        self.data = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_data(&mut self) -> &mut ::std::vec::Vec<u8> {
        &mut self.data
    }

    // Take field
    pub fn take_data(&mut self) -> ::std::vec::Vec<u8> {
        ::std::mem::replace(&mut self.data, ::std::vec::Vec::new())
    }
}

impl ::protobuf::Message for NoiseHandshakePayload {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_bytes_into(wire_type, is, &mut self.identity_key)?;
                },
                2 => {
                    ::protobuf::rt::read_singular_proto3_bytes_into(wire_type, is, &mut self.identity_sig)?;
                },
                3 => {
                    ::protobuf::rt::read_singular_proto3_bytes_into(wire_type, is, &mut self.data)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.identity_key.is_empty() {
            my_size += ::protobuf::rt::bytes_size(1, &self.identity_key);
        }
        if !self.identity_sig.is_empty() {
            my_size += ::protobuf::rt::bytes_size(2, &self.identity_sig);
        }
        if !self.data.is_empty() {
            my_size += ::protobuf::rt::bytes_size(3, &self.data);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.identity_key.is_empty() {
            os.write_bytes(1, &self.identity_key)?;
        }
        if !self.identity_sig.is_empty() {
            os.write_bytes(2, &self.identity_sig)?;
        }
        if !self.data.is_empty() {
            os.write_bytes(3, &self.data)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> NoiseHandshakePayload {
        NoiseHandshakePayload::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                    "identity_key",
                    |m: &NoiseHandshakePayload| { &m.identity_key },
                    |m: &mut NoiseHandshakePayload| { &mut m.identity_key },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                    "identity_sig",
                    |m: &NoiseHandshakePayload| { &m.identity_sig },
                    |m: &mut NoiseHandshakePayload| { &mut m.identity_sig },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                    "data",
                    |m: &NoiseHandshakePayload| { &m.data },
                    |m: &mut NoiseHandshakePayload| { &mut m.data },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<NoiseHandshakePayload>(
                    "NoiseHandshakePayload",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static NoiseHandshakePayload {
        static mut instance: ::protobuf::lazy::Lazy<NoiseHandshakePayload> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const NoiseHandshakePayload,
        };
        unsafe {
            instance.get(NoiseHandshakePayload::new)
        }
    }
}

impl ::protobuf::Clear for NoiseHandshakePayload {
    fn clear(&mut self) {
        self.identity_key.clear();
        self.identity_sig.clear();
        self.data.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for NoiseHandshakePayload {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for NoiseHandshakePayload {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x1esrc/io/handshake/payload.proto\"q\n\x15NoiseHandshakePayload\x12!\
    \n\x0cidentity_key\x18\x01\x20\x01(\x0cR\x0bidentityKey\x12!\n\x0cidenti\
    ty_sig\x18\x02\x20\x01(\x0cR\x0bidentitySig\x12\x12\n\x04data\x18\x03\
    \x20\x01(\x0cR\x04dataJ\xa6\x02\n\x06\x12\x04\0\0\x08\x01\n\x08\n\x01\
    \x0c\x12\x03\0\0\x12\n4\n\x02\x04\0\x12\x04\x04\0\x08\x012(\x20Payloads\
    \x20for\x20Noise\x20handshake\x20messages.\n\n\n\n\x03\x04\0\x01\x12\x03\
    \x04\x08\x1d\n\x0b\n\x04\x04\0\x02\0\x12\x03\x05\x08\x1f\n\r\n\x05\x04\0\
    \x02\0\x04\x12\x04\x05\x08\x04\x1f\n\x0c\n\x05\x04\0\x02\0\x05\x12\x03\
    \x05\x08\r\n\x0c\n\x05\x04\0\x02\0\x01\x12\x03\x05\x0e\x1a\n\x0c\n\x05\
    \x04\0\x02\0\x03\x12\x03\x05\x1d\x1e\n\x0b\n\x04\x04\0\x02\x01\x12\x03\
    \x06\x08\x1f\n\r\n\x05\x04\0\x02\x01\x04\x12\x04\x06\x08\x05\x1f\n\x0c\n\
    \x05\x04\0\x02\x01\x05\x12\x03\x06\x08\r\n\x0c\n\x05\x04\0\x02\x01\x01\
    \x12\x03\x06\x0e\x1a\n\x0c\n\x05\x04\0\x02\x01\x03\x12\x03\x06\x1d\x1e\n\
    \x0b\n\x04\x04\0\x02\x02\x12\x03\x07\x04\x13\n\r\n\x05\x04\0\x02\x02\x04\
    \x12\x04\x07\x04\x06\x1f\n\x0c\n\x05\x04\0\x02\x02\x05\x12\x03\x07\x04\t\
    \n\x0c\n\x05\x04\0\x02\x02\x01\x12\x03\x07\n\x0e\n\x0c\n\x05\x04\0\x02\
    \x02\x03\x12\x03\x07\x11\x12b\x06proto3\
";

static mut file_descriptor_proto_lazy: ::protobuf::lazy::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::lazy::Lazy {
    lock: ::protobuf::lazy::ONCE_INIT,
    ptr: 0 as *const ::protobuf::descriptor::FileDescriptorProto,
};

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    unsafe {
        file_descriptor_proto_lazy.get(|| {
            parse_descriptor_proto()
        })
    }
}
