[package]
name = "libp2p-gossipsub"
version = "0.1.0"
authors = ["Age Manning <age@agemanning.com>"]
license = "MIT"

[dependencies]
libp2p-core = { path = "../../core" }
libp2p-floodsub = { path = "../floodsub" }
bs58 = "0.2.2"
bytes = "0.4.11"
byteorder = "1.3.1"
cuckoofilter = "0.3.2"
fnv = "1.0.6"
futures = "0.1.25"
protobuf = "2.2.5"
rand = "0.6.4"
smallvec = "0.6.8"
tokio-codec = "0.1.1"
tokio-io = "0.1.11"
tokio-timer = "0.2.8"
unsigned-varint = "0.2.1"
log = "0.4.6"


[dev-dependencies]
libp2p = { path = "../../" }
tokio = "0.1"
tokio-stdin-stdout = "0.1"
env_logger = "0.6.0"
