[package]
name = "libp2p-gossipsub"
edition.workspace = true
rust-version = { workspace = true }
description = "Gossipsub protocol for libp2p"
version = "0.49.0"
authors = ["Age Manning <Age@AgeManning.com>"]
license = "MIT"
repository = "https://github.com/libp2p/rust-libp2p"
keywords = ["peer-to-peer", "libp2p", "networking"]
categories = ["network-programming", "asynchronous"]

[features]
wasm-bindgen = ["getrandom/js", "futures-timer/wasm-bindgen"]

[dependencies]
async-channel = "2.3.1"
asynchronous-codec = { workspace = true }
base64 = "0.22.1"
byteorder = "1.5.0"
bytes = "1.6"
either = "1.11"
fnv = "1.0.7"
futures = { workspace = true }
futures-timer = "3.0.2"
getrandom = { workspace = true }
hashlink = { workspace = true }
hex_fmt = "0.3.0"
web-time = { workspace = true }
# Libp2p crates, updated to use crates.io versions so that we can use this gossipsub fork with
# crates.io libp2p
libp2p-core = "0.43"
libp2p-identity = { version = "0.2", features = ["rand"] }
libp2p-swarm = "0.46"
quick-protobuf = "0.8"
quick-protobuf-codec = "0.3.1"
rand = "0.8"
regex = "1.10.5"
serde = { version = "1", optional = true, features = ["derive"] }
sha2 = "0.10.8"
tracing = { workspace = true }
delay_map = "0.4"
hex = "0.4"


# Metrics dependencies
prometheus-client = { workspace = true }

[dev-dependencies]
libp2p-swarm-test = "0.5.0"
quickcheck = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
tokio = { workspace = true, features = ["rt", "rt-multi-thread", "time", "macros"] }

# Passing arguments to the docsrs builder in order to properly document cfg's.
# More information: https://docs.rs/about/builds#cross-compiling
[package.metadata.docs.rs]
all-features = true

[lints]
workspace = true
